### PR TITLE
Fix Delete Command Popup windows

### LINKED ISSUE #217: Alpha-bug: Delete pop-up window appears multiple times
Image

Image

**Issues:**
* Delete pop-up window appear multiple times which could cause error in contact deletion process

**Suggestions:**
* Perhaps we can implement a way to prevent users from clicking away from the pop-up window so user must finish their action within the pop-up window before being able to interact with the main window

### PR DESCRIPTION
**Pull request by yalasoo**
- Update the case for invalid index -> no popup, only error shown inside command box
- Make sure always only one delete popup window is available. User has to give input or esc/enter to retain access to main window. This also addresses the issue for main window closes but popup window remains.
- Update css of popup windows:

  - person list card size follow the same format as the main window
  - invalid input shown as red in input field
 
Screenshot 2025-10-29 at 22 04 08

Closes #217 #231 #136

### CODE REVIEW

File: src/main/java/seedu/address/logic/parser/DeleteCommandParser.java [hunk 1]
```diff
@@ -32,6 +33,10 @@ public DeleteCommandParser(InfoPopupHandler infoPopupHandler, DeletePopupHandler
      */
     public DeleteCommand parse(String args) throws ParseException {
 
+        ArgumentMultimap argMultimap = ArgumentTokenizer.tokenize(args, PREFIX_NAME);
+
+        argMultimap.verifyNoDuplicatePrefixesFor(PREFIX_NAME);
+
```
Comment (TheresiaOng) [inline src/main/java/seedu/address/logic/parser/DeleteCommandParser.java]: Great way to prevent multiple argument. Good job!

File: src/main/java/seedu/address/ui/DeletePopup.java [hunk 2]
```diff
@@ -37,8 +40,12 @@ public class DeletePopup extends UiPart<Stage> {
     public DeletePopup(Stage root) {
         super(FXML, root);
         setUpKeyboardHandlers();
+        inputField.textProperty().addListener((unused1, unused2, unused3) -> setStyleToDefault());
+
         root.setWidth(500);
         root.setHeight(500);
+        root.initModality(Modality.APPLICATION_MODAL);
+        root.setAlwaysOnTop(true);
```
Comment (TheresiaOng) [inline src/main/java/seedu/address/ui/DeletePopup.java]: Nice way to prevent user from interacting with other windows. Good job!
