### PR TITLE
Fix Attendance Alpha-bug messages & mismatch months in view window

### LINKED ISSUE #178: Alpha-bug: Attendance marking display message for colleagues
Image

Perhaps when marking attendance for colleagues, can change the display / success message to 
`Person is a colleague, attendance is not taken.`

### LINKED ISSUE #179: Alpha-bug: The next arrow doesn't go to the next month
**How to replicate:**
- View a contact
- Press left and right keys

**Expected:**
- Left right arrows increase or decrease the month by one. i.e. October to Sept/Nov

**Actual:**
- When I click left arrow (to go back), it went from October 2025 to Feb 2025 instead of Sept 2025

https://github.com/user-attachments/assets/3d36290c-7e7b-423b-820e-4c9351eda99f

### LINKED ISSUE #204: Alpha-Bug: Attendance command improve commandResult
Instead of saying `attendance marked,` perhaps can specify the indexes it was marked for (exclude indexes of colleagues). This is so that users can also remember which indexes they just marked for. 

Image

### PR DESCRIPTION
**Pull request by TheresiaOng**
image
image

**Updates:**
* Attendance will throw an error if index(es) given are all colleagues
* Improve command result messages to display number of students marked
* Index(es) will now be sorted first before marking is called on each one
* Resolve mismatch months displayed in attendance panel inside view window

**Related Issues:**
* Closes #178 
* Closes #204 
* Closes #179

### CODE REVIEW

File: src/test/java/seedu/address/logic/commands/AttendanceCommandTest.java [hunk 1]
```diff
@@ -48,44 +51,62 @@ public void constructor_nullStatus_throwsNullPointerException() {
...
+        AttendanceCommand command = new AttendanceCommand(indexes, date, AttendanceStatus.PRESENT);
 
         CommandResult result = command.execute(model);
 
-        assertEquals(AttendanceCommand.MESSAGE_SUCCESS, result.getFeedbackToUser());
-        // Verify attendance was marked (you might need to check the person's attendance)
+        assertTrue(result.getFeedbackToUser().contains("Marked"));
+        assertTrue(result.getFeedbackToUser().contains("out of"));
+        assertTrue(result.getFeedbackToUser().contains("PRESENT"));
+        assertTrue(result.getFeedbackToUser().contains("12-12-2025"));
```
Comment (deepa-m1) [inline src/test/java/seedu/address/logic/commands/AttendanceCommandTest.java]: Good use of defensive check!
